const path = require('path')
const ConfigModule = require('./config')
// const { apiPathQuery, modulePathQuery } = require('./path-query')
// const { apiProjectHistory, moduleProjectHistory } = require('./project')
// const { apiSample, moduleSample } = require('./sample')
// const { apiExport, moduleExport } = require('./export')

const log = require('../core/logger').createLogger('app')

/**
 * Starts the boot procedure for the application
 * @param {string} appRootPath: where the executable is located
 * @returns {Promise<boolean>}: false means 'severe error', so app must be closed
 */
const boot = async ({ appRootPath }) => {
  log.info('Booting the application...')
  if (await ConfigModule.boot(path.join(appRootPath, 'config.json')) !== true) return false
  return true
}

/**
 * Cleans many files generated by the application
 * @returns {Promise<boolean>}
 */
const clean = async () => {
  log.info('Cleaning application files...')
  await ConfigModule.clean()
  return true
}

module.exports = {
  boot,
  clean,

  API: {
    config: ConfigModule.API.config
  }
}
